# Generated by Django 3.1.5 on 2021-02-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyorder', '0002_buyorder_debt'),
        ('customer', '0002_city'),
        ('sellorder', '0003_auto_20210209_1930'),
        ('supplier', '0001_initial'),
        ('payments', '0002_auto_20210113_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pay_status', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=8)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyorder.buyorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SellOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pay_status', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=8)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellorder.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplierpayment',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='customercheque',
            name='customerpayment',
        ),
        migrations.RemoveField(
            model_name='suppliercheque',
            name='supplierpayment',
        ),
        migrations.DeleteModel(
            name='CustomerPayment',
        ),
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
        migrations.AddField(
            model_name='customercheque',
            name='sellorderpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.sellorderpayment'),
        ),
        migrations.AddField(
            model_name='suppliercheque',
            name='buyorderpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.buyorderpayment'),
        ),
    ]
