# Generated by Django 3.1.5 on 2021-06-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210621_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorderpayment',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Versement', 'Versement')], default='Cash', max_length=9),
        ),
    ]
