# Generated by Django 3.1.5 on 2021-10-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_enterprise_matriculation'),
        ('payments', '0007_servicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderpayment',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Verement', 'Verement')], default='Cash', max_length=9),
        ),
        migrations.AlterField(
            model_name='sellorderpayment',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Verement', 'Verement')], default='Cash', max_length=9),
        ),
        migrations.CreateModel(
            name='CustomerVerment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verment_number', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('sellorderpayment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.sellorderpayment')),
            ],
        ),
    ]
