# Generated by Django 3.1.5 on 2022-02-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220209_1529'),
        ('payments', '0008_auto_20211004_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.serviceprovider'),
        ),
    ]
