# Generated by Django 3.1.5 on 2022-02-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_avancements'),
        ('payments', '0009_auto_20220209_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorderpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer.customer'),
        ),
    ]
