# Generated by Django 3.1.5 on 2022-06-22 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20220227_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorderpayment',
            name='pay_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
