# Generated by Django 3.1.5 on 2022-06-22 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20220622_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderpayment',
            name='pay_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='pay_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
