BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                XXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXX
                XXXXXXXX

                XXXXXXX
                BBB BBBBBBBB BB BBBBBBBBB
                XXXX
                   XXXX
                       
                       
                   XXXXX
                    XXXX
                        XX XXXXXXXXXX XXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXXXXXXX
                    XXXXX

                XXXXX

                BBBBBB
                XXXXXXXX

            XXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXX
BBBBBBBB
BBBBB BBBBBBBB
XXXX XXXXXX XXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXX XXXXX  XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX XXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX

XXXXXXXXX
BBBBBBBB