# Generated by Django 3.1.5 on 2021-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
