# Generated by Django 3.1.5 on 2021-07-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210707_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
