# Generated by Django 3.1.5 on 2022-05-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210714_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
