BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XXXXXXX
                    XXXX
                        XXXXXXXXXXXXXX
                        XXXXXXXXXXXXX
                        XXXXXXXXXXXXXX
                        XXXXXXXXX
                        XXXXXXXXX
                    XXXXX
                    XXXXXXXX
                    XXXXXXX
                    BBB BBBB BB BBBBB
                    XXXX
                        XXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXXXX XXXXXX
                                 XXXXXXX
                        XXXXX
                        XXXX
                            
                        XXXXX

                        XXXX
                            
                        XXXXX
                        XXXX
                            XX XXXXXXXXXX XXXXXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXXX
                        XXXXX
                        XXXX
                            XX XXXXXXXXXX XXXXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXXX
                        XXXXX
                    XXXXX
                    BBBBBB
                    XXXXXXXX

                XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
BBBBB BBBBBBBB
XXXX XXXXXX XXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXX XXXXX  XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX XXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX


XXXXXXXXX
BBBBBBBB