BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXX

XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX

    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX

            XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                FFFFFF
                XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
        BB BBBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBBBBBB
        BBB BBBBB BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXX FFFFFFXXXXXXXXX
        XXXXXX
        BBBBBB
        BBBBBB
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXFFFFFFXXXXXXXXX
        XXXXXX
        BBBBBB
        BBBBB


    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX

    XXXXXX
XXXXXX
XXXXXX

XXXXXXXX

	XXXXXXXXX
BBBBBBBB