BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX

XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                BBB BBB BB BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXX
                                 XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX

                   XX XXXXXXXXXX XXXXXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXXXXXXXX
                   XX XXXXXXXXXX XXXXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXXXXXXXX

                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX

    XXXXXX

XXXXXX

BBBBBBBB
