# Generated by Django 3.1.5 on 2021-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210403_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
