# Generated by Django 3.1.5 on 2021-06-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='article_imposition',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='art',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='nif',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='nis',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='rc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
