# Generated by Django 3.1.5 on 2021-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210615_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='num_account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
