# Generated by Django 3.1.5 on 2021-06-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_enterprise_num_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='num_account',
            new_name='num_account_bancaire',
        ),
    ]
