# Generated by Django 3.1.5 on 2021-06-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210615_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='num_account_bancaire',
            new_name='num_compte_bancaire',
        ),
    ]
