# Generated by Django 3.1.5 on 2021-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210615_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='num_compte_bancaire',
            new_name='N_compte',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='ai_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='art_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='nif_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='nis_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='rc_check',
            field=models.BooleanField(default=False),
        ),
    ]
