# Generated by Django 3.1.5 on 2021-06-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210619_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='matriculation',
            field=models.BooleanField(default=False),
        ),
    ]
