# Generated by Django 3.1.5 on 2022-01-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_enterprise_matriculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avancements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancement', to='customer.customer')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_avancement', to='customer.enterprise')),
            ],
        ),
    ]
