# Generated by Django 3.1.5 on 2021-02-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
