# Generated by Django 3.1.5 on 2021-02-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210207_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellpricenormal',
            new_name='sellprice',
        ),
    ]
