# Generated by Django 3.1.5 on 2021-08-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210705_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
