# Generated by Django 3.1.5 on 2021-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellorder', '0003_auto_20210209_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
