# Generated by Django 3.1.5 on 2021-02-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20210207_1835'),
        ('stock', '0003_remove_stockproduct_category'),
        ('customer', '0002_city'),
        ('sellorder', '0005_auto_20210210_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicule.vehicle'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stockproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_item', to='stock.stockproduct'),
        ),
    ]
