# Generated by Django 3.1.5 on 2021-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellorder', '0006_auto_20210210_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
