# Generated by Django 3.1.5 on 2021-02-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_auto_20210210_1135'),
        ('sellorder', '0007_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanneItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='sellorder.order')),
                ('panne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_panne', to='rdv.panne')),
            ],
        ),
    ]
