# Generated by Django 3.1.5 on 2021-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellorder', '0012_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factured',
            field=models.BooleanField(default=False),
        ),
    ]
