# Generated by Django 3.1.5 on 2021-03-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellorder', '0013_order_factured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOrderFacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellorder.order')),
            ],
        ),
    ]
