# Generated by Django 3.1.5 on 2021-03-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellorder', '0014_sellorderfacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timbre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
