# Generated by Django 3.1.5 on 2021-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellorder', '0016_serviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
