# Generated by Django 3.1.5 on 2021-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellorder', '0018_auto_20210811_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
