# Generated by Django 3.1.5 on 2022-01-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_enterprise_matriculation'),
        ('sellorder', '0020_auto_20210816_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='customer.customer'),
        ),
    ]
