# Generated by Django 3.1.5 on 2022-02-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220209_1529'),
        ('sellorder', '0021_auto_20220123_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provided_item', to='services.serviceprovider'),
        ),
    ]
