# Generated by Django 3.1.5 on 2022-05-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellorder', '0024_auto_20220510_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='buy_price',
        ),
    ]
