# Generated by Django 3.0.6 on 2021-01-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='brands/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='types/%Y/%m/%d')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Brand')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VehiculeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200, null=True)),
                ('vehicle_mat', models.CharField(max_length=200, null=True)),
                ('vehicle_cart_gris', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('customerNew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerNew', to='customer.Customer')),
                ('customerOld', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerOld', to='customer.Customer')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200, null=True)),
                ('vehicle_mat', models.CharField(max_length=200, null=True)),
                ('vehicle_cart_gris', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Type')),
            ],
        ),
    ]
