# Generated by Django 3.1.5 on 2021-02-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20210207_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
