# Generated by Django 3.1.5 on 2021-02-13 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellorder', '0007_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_status', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='Percentage', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sellorder.order')),
            ],
        ),
    ]
