BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXX XXX XXXXXXXXXXX XX XXXX
XX XXXXXXXXXXXX XXXXXXXXXXXX XX XX
XX XXXXXXXXXXXX XXXXXXXXXXXXXXX
XXX
BBBBB BBBBBBB


XXXX
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX

    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX

            XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                 FFFFFF
                XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXX FFFFFFXXXXXXXXX
        XXXXXX
        BBBBBB
        BBBBBB
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXFFFFFFXXXXXXXXX
        XXXXXX
        BBBBBB
        BBBBB


    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX

    XXXXXX
XXXXXX
XXXXXXXX

	XXXXXXXXX
BBBBBBBB
