BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXXXX
                XXXXXXXX
                XXXXXXX
                BBB BBB BB BBBBBBBBBBBBBBBBB
                XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                XXXXX
                BBBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
BBBBB BBBBBBBB
XXXX XXXX XXXXX  XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX XXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX

XXXXXXXXX
BBBBBBBB