BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXX XXXX XXX XXXX XX XXXXXX XXXX
            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX
XXXXXX


XXXXXXXX

XXXXXXXXX
BBBBBBBB