BBBB BBBBBB
XXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXX

XXXXX X
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XX
X

XXXXX XXX XXXXX XX X
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXX XXXXX
X

XXXXX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX
X

XXXXX XXX XXXXX XXXXXXXX X
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
X

XXXXXXXXXX X
    XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
X

XXXX X
    XXXXXXXXXXXXXXXXX
X


  XXXXXXXX
XXXXXXX
XXXXXX
XXXXXX XXXXXXXXXXX
XXX
    XXXXXXXXXXX XXX XXXXX
    XXXXX XXXXXXXXXXXXXXXXXX
        FFFFFFF FF FF
    XXXXXXX
XXXX
XXXXXXX XXXXXXX
XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX XXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X XXXXXXX
XXXX
XXXXXXXXXXXXXXXX
XXX
    XXXXX XXXXXXXX XXXX X XXXXXXXX
    XXXXX XXXXXXXX XXXX X XXXXXXXXXXX
    XXXXX XXXXXXXX XXX X XXXXXXXXXXX
    XXXXX XXXXXXXX XXXXX XXXXX X XXXXXXXXXXX
XXXX
BB BBBBBBBBBBBBB
XXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXXXX
    XXXX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
    XXXXX
    XXXXXXXX
    XXXXXXX

    BBB BBBB BB BBBBBBBBBBBBB
    XXX XXXXXXXXXXBBBBB BBB BBB XX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXX
    XXXXX
    BBBBBB
    XXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXX
    XXXXX

    XXXXXXXX
XXXXXXXX
BBBBB
XXXXXXX
XXXXXXX