BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
              XXXXXXX
              XXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                XXXXX
              XXXXXXXX
                XXXXXXX
                BBB BBBB BB BBBBBBBBBBBBB
                XXXX
                    XXXX
                       
                   XXXXX
                    XXXX
                       
                   XXXXX
                    XXXX
                       
                   XXXXX
                    XXXX
                       
                   XXXXX

                    XXXX
                        XX XXXXXXXXXX XXXXXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXXX
                    XXXXX
                    XXXX
                        XX XXXXXXXXXX XXXXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXXX
                    XXXXX
                XXXXX
                BBBBBB
                XXXXXXXX

            XXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXX
BBBBBBBB
BBBBB BBBBBBBB
XXXX XXXXXX XXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXX XXXXX  XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX XXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX

XXXXXXXXX
BBBBBBBB