BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB

XXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBB
                    XX
                       BB BBBBBBBB BB B
                        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                       BBBB
                       XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                       BBBBB
                       XXXXXXXXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXX
                BBB BBBBBBBBBBBB BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX

                    XXXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX
                             XXXXXX
                             XXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXXXX
                        XX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                        XXXX
                        BB BBBBBBBBBBBB BB BBBBBB
                        XXX XXXXXXXXXXXXX XXX XXXXX
                        BBBB BBBBBBBBBBBB BB BBBBBBBBBBB
                        XXX XXXXXXXXXXXXX XXXXXXXX
                        BBBB BBBBBBBBBBBB BB BBBBBBBBBB
                        XXX XXXXXXXXXXXXX XXXXXXXX
                        BBBB BBBBBBBBBBBB BB BBBBBBBBB
                        XXX XXXXXXXXXXXXX XXXXXXXX
                        BBBB
                        XXX XXXXXXXXXXXXXXXXXXX
                        BBBBB
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXX
                           XXXXXX BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXX
                            XX
                                    XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXX
                        XXXX

                    XXXXXX
                    XXXX  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX


                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX

XXXXXXXXX
BBBBBBBB