BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXX
            XXXXX XXXXXXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                FFFFFF
                XXXX XXXXXXXXXX XXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXXX
        XXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXFFFFFFXXXXXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

XXXXXX

BBBBBBBB