BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
XXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXXXXX
                XXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                XXXXX
                XXXXXXXX
                XXXXXXX
                BBB BBBBB BB BBBBBB

                XXXX
                   XXXX
                       XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXX XXXXXXX
                   XXXXX

                    XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBXX
                       
                            XXXX
                   XXXXX

                    XXXX
                        XX XXXXXXXXXX XXXXXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXXXX
                    XXXXX
                    XXXX
                        XX XXXXXXXXXX XXXXXXXXXX X XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXXXX
                    XXXXX
                XXXXX
                BBBBBB
                XXXXXXXX

            XXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
XXXXXX
BBBBBBBB
BBBBB BBBBBBBB
XXXX XXXXXX XXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXX XXXXX  XXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX XXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
X XX

XXXXXXXXX
BBBBBBBB