# Generated by Django 3.1.5 on 2021-02-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210207_1841'),
        ('supplier', '0001_initial'),
        ('buyorder', '0003_auto_20210210_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorder',
            name='factured',
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='buyorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyorder_item', to='product.product'),
        ),
    ]
