# Generated by Django 3.1.5 on 2021-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyorder', '0008_auto_20210318_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
