# Generated by Django 3.1.5 on 2021-08-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210811_0758'),
        ('buyorder', '0010_auto_20210714_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyorder_item', to='product.product'),
        ),
    ]
