# Generated by Django 3.1.5 on 2021-08-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210714_0932'),
        ('buyorder', '0011_auto_20210811_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorderitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_stocks', to='stock.stock'),
        ),
    ]
