# Generated by Django 3.1.5 on 2022-02-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210818_1643'),
        ('buyorder', '0013_auto_20220127_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyorder_item', to='product.product'),
        ),
    ]
