# Generated by Django 3.1.5 on 2021-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='rdv_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdv',
            name='rdv_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
