BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB

XXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXX XXXX XXX XXXX XX XXXXXX XXXX
            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXX

                BBBBBBBBBB
                XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX
                XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX
XXXXXX

BBBBBBBB